image: steveblackburn/comp1110-2020-s2-gitlab-ci:0.1.1

stages:
  - build
  - test

before_script:
  - export CP=src:/mse/comp1110-mse.jar:/mse/hamcrest-core-1.3.jar:/mse/junit-4.12.jar

build:
  tags:
    - comp1110
  stage: build
  script:
    - javac -encoding utf-8 $JAVAFX_OPTIONS -cp $CP src/comp1110/mse/*.java
  artifacts:
    paths:
      - src/comp1110/mse/*.class

Q1:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.mse.Q1ProductTest
  allow_failure: true

Q2:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.mse.Q2MeterTest
  allow_failure: true

Q3:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.mse.Q3ShapesTest
  allow_failure: true

Q4:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.mse.Q4BridgesTest
  allow_failure: true

